version: "3.8"

services:
  dicom-management-service:
    image: dicom:latest
    container_name: dicom-management-service
    build:
      context: ./dicom_management_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - UPLOAD_DIR=/uploads
    volumes:
      - dicom_uploads:/uploads

volumes:
  dicom_uploads:
    driver: local
