version: "3.8"

services:
  image-management-service:
    image: ims:latest
    container_name: image-management-service
    ports:
      - 3000:3000
    build:
      context: ./ImageManagementService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

networks:
  default:
    driver: bridge
